### ISSUE TITLE
FEATURE: Adding pypi/rtd/travis badges to README

### ISSUE THREAD

**Issue by pstauffer** [confirm/ansibleci#15]
Maybe we could integrate some shields (http://shields.io/) in our readme page.

I've added the build-status, pypi version and downloads per month to my fork to test it.

Check it out:
https://github.com/pstauffer/ansibleci/blob/develop/README.rst

**Comment by pstauffer** [comment]
btw. the pypi version seems to be wrong

**Comment by domibarton** [comment]
There's already a badge available for rtd, but I didn't implement it so far. Would be great to get badges for the other stuff as well.

Which PyPi version you're referring to? It's already bumped to v1.0.0 in `develop`, because this is the next release. I think the `develop` branch is always "bleeding edge" and therefor doesn't (or shouldn't) point to the latest stable version. Or to be more precise, it _can_ point to the latest stable version but only until the new release is prepared, so there's no guarantee :) Though, the `master` branch should always point to the latest stable version (tags are also made there). However, I forgot to change the version in the [sphinx docs config](docs/conf.py) for `v0.2.0` but it should be correct in the next release.

**Comment by domibarton** [comment]
Btw I would suggest to create feature branches and not forks to test things. IMHO It's easier (at least for us collaborators) and you can refer issues with the hash-thingy.

**Comment by pstauffer** [comment]
I would have use a feature branch to test it, but I haven't got access to the github confirm account to add permissions for integrations.

**Comment by domibarton** [comment]
Just checked pypi.org. There was a 1.0.0 version from testing, but it should be removed now. However, v1.0.0 is still visible in the badge :/

**Comment by domibarton** [comment]
Don't get it with the github privileges. You already had admin access to the repo, but apparently this wasn't enough :) You should no have admin (owner) access to the organisation as well.
